package com.example.livevoicetranslator_rd.domain.model

enum class TranslatableLanguages(
    val title: String,
    val code: String,
) {
    Afrikaans("Afrikaans", "af"),
    Arabic("Arabic", "ar"),
    Belarusian("Belarusian", "be"),
    Bulgarian("Bulgarian", "bg"),
    Bengali("Bengali", "bn"),
    Catalan("Catalan", "ca"),
    Czech("Czech", "cs"),
    Welsh("Welsh", "cy"),
    Danish("Danish", "da"),
    German("German", "de"),
    Greek("Greek", "el"),
    Spanish("Spanish", "es"),
    English("English", "en"),
    Estonian("Estonian", "et"),
    Basque("Basque", "eu"),
    Persian("Persian", "fa"),
    Finnish("Finnish", "fi"),
    French("French", "fr"),
    Irish("Irish", "ga"),
    Galician("Galician", "gl"),
    Gujarati("Gujarati", "gu"),
    Hebrew("Hebrew", "he"),
    Hindi("Hindi", "hi"),
    Croatian("Croatian", "hr"),
    Hungarian("Hungarian", "hu"),
    Indonesian("Indonesian", "id"),
    Icelandic("Icelandic", "is"),
    Italian("Italian", "it"),
    Japanese("Japanese", "ja"),
    Georgian("Georgian", "ka"),
    Kazakh("Kazakh", "kk"),
    Kannada("Kannada", "kn"),
    Korean("Korean", "ko"),
    Lithuanian("Lithuanian", "lt"),
    Latvian("Latvian", "lv"),
    Malayalam("Malayalam", "ml"),
    Marathi("Marathi", "mr"),
    Malay("Malay", "ms"),
    Burmese("Burmese", "my"),
    Nepali("Nepali", "ne"),
    Dutch("Dutch", "nl"),
    Norwegian("Norwegian", "no"),
    Punjabi("Punjabi", "pa"),
    Polish("Polish", "pl"),
    Portuguese("Portuguese", "pt"),
    Romanian("Romanian", "ro"),
    Russian("Russian", "ru"),
    Slovak("Slovak", "sk"),
    Slovenian("Slovenian", "sl"),
    Somali("Somali", "so"),
    Albanian("Albanian", "sq"),
    Serbian("Serbian", "sr"),
    Swedish("Swedish", "sv"),
    Swahili("Swahili", "sw"),
    Tamil("Tamil", "ta"),
    Telugu("Telugu", "te"),
    Thai("Thai", "th"),
    Tagalog("Tagalog", "tl"),
    Turkish("Turkish", "tr"),
    Ukrainian("Ukrainian", "uk"),
    Urdu("Urdu", "ur"),
    Vietnamese("Vietnamese", "vi"),
    ChineseSimplified("Chinese (Simplified)", "zh"),
    ChineseTraditional("Chinese (Traditional)", "zh-Hant")
}
