package com.example.livevoicetranslator_rd.domain.model

enum class TranslateLanguage {
    AFRIKAANS, ARABIC, BELARUSSIAN, BULGARIAN, BENGALI,
    CATALAN, CZECH, WELSH, DANISH, GERMAN, GREEK, ENGLISH, ESPERANTO,
    SPANISH, ESTONIAN, PERSIAN, FINNISH, FRENCH, IRISH, GALICIAN,
    GUJARATI, HEBREW, HINDI, CROATIAN, HAITIAN, HUNGARIAN, INDONESIAN,
    ICELANDIC, ITALIAN, JAPANESE, GEORGIAN, KANNADA, KOREAN,
    LITHUANIAN, LATVIAN, MACEDONIAN, MARATHI, MALAY, MALTESE,
    DUTCH, NORWEGIAN, POLISH, PORTUGUESE, ROMANIAN, RUSSIAN,
    SLOVAK, SLOVENIAN, ALBANIAN, SWEDISH, SWAHILI, TAMIL,
    TELUGU, THAI, TAGALOG, TURKISH, UKRAINIAN, URDU, VIETNAMESE, CHINESE
}